TAP_DANCE_ENABLE = yes      # enable Tap dance
BOOTMAGIC_ENABLE = no       # disable Bootmagic Lite
MIDI_ENABLE = no            # disable MIDI controls
AUDIO_ENABLE = no           # disable Audio
KEY_OVERRIDE_ENABLE = yes   # enable key overrides
CAPS_WORD_ENABLE = yes      # enable caps word
COMBO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
LEADER_ENABLE = yes
